### ISSUE TITLE
Prototyping: IR Distance Sensor

### ISSUE THREAD

**Issue by nicojopr** [FRC2706/2020-2706-Robot-Code#15]

**Comment by kevlam2706** [comment]
Deliverable here is to create a wrapper class for the Sharp IR sensor that allows us to get either the raw voltage reading or a calculated distance value based on an equation which we can determine. Note that if we do provide a calculated distance, we need to test it and understand how accurate it is in real world conditions.

**Comment by Citysurvivor** [comment]
Code is done, tested (IR sensor equation tested on a roborio), and builds successfully. Looks like I can go ahead and close this issue now.
