### ISSUE TITLE
Indexer Subsystem

### ISSUE THREAD

**Issue by nicojopr** [FRC2706/2020-2706-Robot-Code#48]
Production software for the indexer subsystem in the robot code, including:
- interface definitions, motors, sensors
- commands
- etc..
- tested independently
- merged and integrated with 2020 robot code in github
- ready for integration

**Comment by kevlam2706** [comment]
I just noticed that the Feeder wheel may be separate from the Indexer wheel. In the prototype the two were tied together by a belt. I’ve asked on Slack to clarify if the real one will be separately controlled, in which case we will need to add a second motor to this subsystem and include in the commands the logic to manage the timing and sequencing between them.

**Comment by nrgill28** [comment]
Is this a dupe of #34

**Comment by nicojopr** [comment]
Duplicate of #34 ...closing
