### ISSUE TITLE
List of Autonomous Modes

### ISSUE THREAD

**Issue by nicojopr** [FRC2706/2020-2706-Robot-Code#51]
Brainstorm with previous drive team and other interested members on potential mode of operations desired for autonomous mode (first 15 seconds of the match, no driver). Scenarios that have been mentionned at various team meetings so far:

- basic drive off the initiation line
- score 3 high power cells (pre-loaded)
...

Outcome of this task is a prioritized list of modes that could be made available for competition

**Comment by nicojopr** [comment]
Add the list to our wiki and request review/discussion at a software team meeting (Wed?)

**Comment by Zinka010** [comment]
So another obvious one is do nothing and wait then high goal

**Comment by Zinka010** [comment]
List avaialable at https://github.com/FRC2706/2020-2706-Robot-Code/wiki/Autonomous-Modes

**Comment by kevlam2706** [comment]
I made some edits to the list to add "move off initiation line" to the high goal autos. We probably want those 5 points :smiley:

**Comment by nicojopr** [comment]
This documentation task is considered done, new tasks are created for the specific autonomous modes
