### ISSUE TITLE
Dynamic Variable Config

### ISSUE THREAD

**Issue by nicojopr** [FRC2706/2020-2706-Robot-Code#6]
Design the robot software to be able to be deployed on multiple robots with different configurations. This could mean using constants for multiple robots.

**Comment by nicojopr** [comment]
See also section Robot Configuration in last year's design doc at [Software Subteam doc](https://docs.google.com/document/d/1g-gRJl5WSKs02p0enl25fNy3bzM4tkNJwyIPzVfcBS0/edit#heading=h.8ftaqdnd0io)

**Comment by nicojopr** [comment]
Is this the same as [Issue #31 ](https://github.com/FRC2706/2020-2706-Robot-Code/projects/1#card-31576221) ?

**Comment by georgetzavelas** [comment]
Yes this is the same thing.
