### ISSUE TITLE
Add first cut of preset positions to operator arm control

### ISSUE THREAD

**Issue by kevlam2706** [FRC2706/2020-2706-Robot-Code#78]
Using the winch prototype on the table at the barn, set up a couple of preset positions in the arm subsystem and commands to go up/down either manually or from position to position (like last year's elevator).

We should be able to set up:

a zero point ("bottom")
a top position representing vertical extension, which is set as a soft limit
3 intermediate positions in between the two extremes.

Set up the code so that these positions can be quickly adjusted as constants within the arm subsystem, potentially as fluid constants.

Set the constants to work with the table elevator prototype.

**Comment by nicojopr** [comment]
Cancelled, will work with the real 2020 robots via task #33
